import 'package:two_miners_api/two_miners_api.dart';

enum RepositoryIndex {
  initial,
  eth,
  ethSolo,
  rvn,
  rvnSolo,
  etc,
  etcSolo,
  xmr,
  xmrSolo,
  erg,
  ergSolo,
  btg,
  btgSolo,
  ctxc,
  ctxcSolo,
  ckb,
  ckbSolo,
  firo,
  firoSolo,
  flux,
  fluxSolo,
  zec,
  zecSolo,
  beam,
  beamSolo,
  grin,
  grinSolo,
  clo,
  cloSolo,
  zen,
  zenSolo,
  ae,
  aeSolo,
  etp,
  etpSolo,
  mwc,
  mwcSolo,
  exp,
  expSolo,
}

class CoinRepositories {
  Map<RepositoryIndex, BaseRepository> get repositories => {
        RepositoryIndex.eth: ETHRepository(),
        RepositoryIndex.ethSolo: ETHSoloRepository(),
        RepositoryIndex.rvn: RVNRepository(),
        RepositoryIndex.rvnSolo: RVNSoloRepository(),
        RepositoryIndex.etc: ETCRepository(),
        RepositoryIndex.etcSolo: ETCSoloRepository(),
        RepositoryIndex.xmr: XMRRepository(),
        RepositoryIndex.xmrSolo: XMRSoloRepository(),
        RepositoryIndex.erg: ERGRepository(),
        RepositoryIndex.ergSolo: ERGSoloRepository(),
        RepositoryIndex.btg: BTGRepository(),
        RepositoryIndex.btgSolo: BTGSoloRepository(),
        RepositoryIndex.ctxc: CTXCRepository(),
        RepositoryIndex.ctxcSolo: CTXCSoloRepository(),
        RepositoryIndex.ckb: CKBRepository(),
        RepositoryIndex.ckbSolo: CKBSoloRepository(),
        RepositoryIndex.firo: FIRORepository(),
        RepositoryIndex.firoSolo: FIROSoloRepository(),
        RepositoryIndex.flux: FLUXRepository(),
        RepositoryIndex.fluxSolo: FLUXSoloRepository(),
        RepositoryIndex.zec: ZECRepository(),
        RepositoryIndex.zecSolo: ZECSoloRepository(),
        RepositoryIndex.beam: BEAMRepository(),
        RepositoryIndex.beamSolo: BEAMSoloRepository(),
        RepositoryIndex.grin: GRINRepository(),
        RepositoryIndex.grinSolo: GRINSoloRepository(),
        RepositoryIndex.clo: CLORepository(),
        RepositoryIndex.cloSolo: CLOSoloRepository(),
        RepositoryIndex.zen: ZENRepository(),
        RepositoryIndex.zenSolo: ZENSoloRepository(),
        RepositoryIndex.ae: AERepository(),
        RepositoryIndex.aeSolo: AESoloRepository(),
        RepositoryIndex.etp: ETPRepository(),
        RepositoryIndex.etpSolo: ETPSoloRepository(),
        RepositoryIndex.mwc: MWCRepository(),
        RepositoryIndex.mwcSolo: MWCSoloRepository(),
        RepositoryIndex.exp: EXPRepository(),
        RepositoryIndex.expSolo: EXPSoloRepository(),
      };
}
